apiVersion: apps/v1
kind: Deployment
metadata:
  name: m114-duration-1h-deadline-4h
  namespace: default
  labels:
    app: m114-duration-1h-deadline-4h
    duration: duration-1h
    deadline: deadline-4h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m114
  template:
    metadata:
      labels:
        name: m114
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 2Gi
            cpu: 2000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m115-duration-3h-deadline-4h
  namespace: default
  labels:
    app: m115-duration-3h-deadline-4h
    duration: duration-3h
    deadline: deadline-4h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m115
  template:
    metadata:
      labels:
        name: m115
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m116-duration-6h-deadline-7h
  namespace: default
  labels:
    app: m116-duration-6h-deadline-7h
    duration: duration-6h
    deadline: deadline-7h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m116
  template:
    metadata:
      labels:
        name: m116
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 2000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m117-duration-1h-deadline-2h
  namespace: default
  labels:
    app: m117-duration-1h-deadline-2h
    duration: duration-1h
    deadline: deadline-2h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m117
  template:
    metadata:
      labels:
        name: m117
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m118-duration-3h-deadline-4h
  namespace: default
  labels:
    app: m118-duration-3h-deadline-4h
    duration: duration-3h
    deadline: deadline-4h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m118
  template:
    metadata:
      labels:
        name: m118
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 2Gi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m119-duration-6h-deadline-7h
  namespace: default
  labels:
    app: m119-duration-6h-deadline-7h
    duration: duration-6h
    deadline: deadline-7h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m119
  template:
    metadata:
      labels:
        name: m119
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m120-duration-1h-deadline-7h
  namespace: default
  labels:
    app: m120-duration-1h-deadline-7h
    duration: duration-1h
    deadline: deadline-7h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m120
  template:
    metadata:
      labels:
        name: m120
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m121-duration-3h-deadline-9h
  namespace: default
  labels:
    app: m121-duration-3h-deadline-9h
    duration: duration-3h
    deadline: deadline-9h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m121
  template:
    metadata:
      labels:
        name: m121
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m122-duration-6h-deadline-12h
  namespace: default
  labels:
    app: m122-duration-6h-deadline-12h
    duration: duration-6h
    deadline: deadline-12h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m122
  template:
    metadata:
      labels:
        name: m122
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 2Gi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m123-duration-1h-deadline-7h
  namespace: default
  labels:
    app: m123-duration-1h-deadline-7h
    duration: duration-1h
    deadline: deadline-7h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m123
  template:
    metadata:
      labels:
        name: m123
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m124-duration-3h-deadline-6h
  namespace: default
  labels:
    app: m124-duration-3h-deadline-6h
    duration: duration-3h
    deadline: deadline-6h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m124
  template:
    metadata:
      labels:
        name: m124
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 2000m
---
