apiVersion: apps/v1
kind: Deployment
metadata:
  name: m019-duration-3h-deadline-9h
  namespace: default
  labels:
    app: m019-duration-3h-deadline-9h
    duration: duration-3h
    deadline: deadline-9h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m019
  template:
    metadata:
      labels:
        name: m019
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m020-duration-6h-deadline-9h
  namespace: default
  labels:
    app: m020-duration-6h-deadline-9h
    duration: duration-6h
    deadline: deadline-9h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m020
  template:
    metadata:
      labels:
        name: m020
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m021-duration-1h-deadline-7h
  namespace: default
  labels:
    app: m021-duration-1h-deadline-7h
    duration: duration-1h
    deadline: deadline-7h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m021
  template:
    metadata:
      labels:
        name: m021
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m022-duration-3h-deadline-9h
  namespace: default
  labels:
    app: m022-duration-3h-deadline-9h
    duration: duration-3h
    deadline: deadline-9h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m022
  template:
    metadata:
      labels:
        name: m022
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m023-duration-6h-deadline-7h
  namespace: default
  labels:
    app: m023-duration-6h-deadline-7h
    duration: duration-6h
    deadline: deadline-7h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m023
  template:
    metadata:
      labels:
        name: m023
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
---
