apiVersion: apps/v1
kind: Deployment
metadata:
  name: m047-duration-6h-deadline-8h
  namespace: default
  labels:
    app: m047
    duration: duration-6h
    deadline: deadline-8h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m047
  template:
    metadata:
      labels:
        name: m047
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m048-duration-1h-deadline-7h
  namespace: default
  labels:
    app: m048
    duration: duration-1h
    deadline: deadline-7h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m048
  template:
    metadata:
      labels:
        name: m048
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m049-duration-3h-deadline-5h
  namespace: default
  labels:
    app: m049
    duration: duration-3h
    deadline: deadline-5h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m049
  template:
    metadata:
      labels:
        name: m049
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m050-duration-6h-deadline-30h
  namespace: default
  labels:
    app: m050
    duration: duration-6h
    deadline: deadline-30h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m050
  template:
    metadata:
      labels:
        name: m050
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m051-duration-1h-deadline-25h
  namespace: default
  labels:
    app: m051
    duration: duration-1h
    deadline: deadline-25h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m051
  template:
    metadata:
      labels:
        name: m051
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m052-duration-3h-deadline-27h
  namespace: default
  labels:
    app: m052
    duration: duration-3h
    deadline: deadline-27h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m052
  template:
    metadata:
      labels:
        name: m052
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m053-duration-6h-deadline-12h
  namespace: default
  labels:
    app: m053
    duration: duration-6h
    deadline: deadline-12h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m053
  template:
    metadata:
      labels:
        name: m053
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m054-duration-1h-deadline-25h
  namespace: default
  labels:
    app: m054
    duration: duration-1h
    deadline: deadline-25h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m054
  template:
    metadata:
      labels:
        name: m054
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m055-duration-3h-deadline-9h
  namespace: default
  labels:
    app: m055
    duration: duration-3h
    deadline: deadline-9h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m055
  template:
    metadata:
      labels:
        name: m055
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m056-duration-6h-deadline-30h
  namespace: default
  labels:
    app: m056
    duration: duration-6h
    deadline: deadline-30h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m056
  template:
    metadata:
      labels:
        name: m056
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m057-duration-1h-deadline-3h
  namespace: default
  labels:
    app: m057
    duration: duration-1h
    deadline: deadline-3h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m057
  template:
    metadata:
      labels:
        name: m057
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m058-duration-3h-deadline-9h
  namespace: default
  labels:
    app: m058
    duration: duration-3h
    deadline: deadline-9h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m058
  template:
    metadata:
      labels:
        name: m058
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m059-duration-6h-deadline-30h
  namespace: default
  labels:
    app: m059
    duration: duration-6h
    deadline: deadline-30h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m059
  template:
    metadata:
      labels:
        name: m059
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m060-duration-1h-deadline-3h
  namespace: default
  labels:
    app: m060
    duration: duration-1h
    deadline: deadline-3h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m060
  template:
    metadata:
      labels:
        name: m060
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m061-duration-3h-deadline-5h
  namespace: default
  labels:
    app: m061
    duration: duration-3h
    deadline: deadline-5h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m061
  template:
    metadata:
      labels:
        name: m061
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m062-duration-6h-deadline-8h
  namespace: default
  labels:
    app: m062
    duration: duration-6h
    deadline: deadline-8h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m062
  template:
    metadata:
      labels:
        name: m062
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m063-duration-1h-deadline-25h
  namespace: default
  labels:
    app: m063
    duration: duration-1h
    deadline: deadline-25h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m063
  template:
    metadata:
      labels:
        name: m063
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m064-duration-3h-deadline-27h
  namespace: default
  labels:
    app: m064
    duration: duration-3h
    deadline: deadline-27h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m064
  template:
    metadata:
      labels:
        name: m064
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m065-duration-6h-deadline-8h
  namespace: default
  labels:
    app: m065
    duration: duration-6h
    deadline: deadline-8h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m065
  template:
    metadata:
      labels:
        name: m065
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m066-duration-1h-deadline-3h
  namespace: default
  labels:
    app: m066
    duration: duration-1h
    deadline: deadline-3h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m066
  template:
    metadata:
      labels:
        name: m066
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
---
