apiVersion: apps/v1
kind: Deployment
metadata:
  name: m164-duration-6h-deadline-30h
  namespace: default
  labels:
    app: m164-duration-6h-deadline-30h
    duration: duration-6h
    deadline: deadline-30h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m164
  template:
    metadata:
      labels:
        name: m164
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m165-duration-1h-deadline-25h
  namespace: default
  labels:
    app: m165-duration-1h-deadline-25h
    duration: duration-1h
    deadline: deadline-25h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m165
  template:
    metadata:
      labels:
        name: m165
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m166-duration-3h-deadline-5h
  namespace: default
  labels:
    app: m166-duration-3h-deadline-5h
    duration: duration-3h
    deadline: deadline-5h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m166
  template:
    metadata:
      labels:
        name: m166
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m167-duration-6h-deadline-12h
  namespace: default
  labels:
    app: m167-duration-6h-deadline-12h
    duration: duration-6h
    deadline: deadline-12h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m167
  template:
    metadata:
      labels:
        name: m167
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m168-duration-1h-deadline-25h
  namespace: default
  labels:
    app: m168-duration-1h-deadline-25h
    duration: duration-1h
    deadline: deadline-25h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m168
  template:
    metadata:
      labels:
        name: m168
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m169-duration-3h-deadline-9h
  namespace: default
  labels:
    app: m169-duration-3h-deadline-9h
    duration: duration-3h
    deadline: deadline-9h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m169
  template:
    metadata:
      labels:
        name: m169
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m170-duration-6h-deadline-30h
  namespace: default
  labels:
    app: m170-duration-6h-deadline-30h
    duration: duration-6h
    deadline: deadline-30h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m170
  template:
    metadata:
      labels:
        name: m170
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m171-duration-1h-deadline-7h
  namespace: default
  labels:
    app: m171-duration-1h-deadline-7h
    duration: duration-1h
    deadline: deadline-7h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m171
  template:
    metadata:
      labels:
        name: m171
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m172-duration-3h-deadline-27h
  namespace: default
  labels:
    app: m172-duration-3h-deadline-27h
    duration: duration-3h
    deadline: deadline-27h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m172
  template:
    metadata:
      labels:
        name: m172
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m173-duration-6h-deadline-8h
  namespace: default
  labels:
    app: m173-duration-6h-deadline-8h
    duration: duration-6h
    deadline: deadline-8h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m173
  template:
    metadata:
      labels:
        name: m173
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m174-duration-1h-deadline-25h
  namespace: default
  labels:
    app: m174-duration-1h-deadline-25h
    duration: duration-1h
    deadline: deadline-25h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m174
  template:
    metadata:
      labels:
        name: m174
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m175-duration-3h-deadline-5h
  namespace: default
  labels:
    app: m175-duration-3h-deadline-5h
    duration: duration-3h
    deadline: deadline-5h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m175
  template:
    metadata:
      labels:
        name: m175
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m176-duration-6h-deadline-12h
  namespace: default
  labels:
    app: m176-duration-6h-deadline-12h
    duration: duration-6h
    deadline: deadline-12h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m176
  template:
    metadata:
      labels:
        name: m176
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m177-duration-1h-deadline-3h
  namespace: default
  labels:
    app: m177-duration-1h-deadline-3h
    duration: duration-1h
    deadline: deadline-3h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m177
  template:
    metadata:
      labels:
        name: m177
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m178-duration-3h-deadline-9h
  namespace: default
  labels:
    app: m178-duration-3h-deadline-9h
    duration: duration-3h
    deadline: deadline-9h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m178
  template:
    metadata:
      labels:
        name: m178
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m179-duration-6h-deadline-12h
  namespace: default
  labels:
    app: m179-duration-6h-deadline-12h
    duration: duration-6h
    deadline: deadline-12h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m179
  template:
    metadata:
      labels:
        name: m179
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m180-duration-1h-deadline-7h
  namespace: default
  labels:
    app: m180-duration-1h-deadline-7h
    duration: duration-1h
    deadline: deadline-7h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m180
  template:
    metadata:
      labels:
        name: m180
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 1000m
---
