apiVersion: apps/v1
kind: Deployment
metadata:
  name: m017-duration-6h-deadline-7h
  namespace: default
  labels:
    app: m017-duration-6h-deadline-7h
    duration: duration-6h
    deadline: deadline-7h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m017
  template:
    metadata:
      labels:
        name: m017
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m018-duration-1h-deadline-4h
  namespace: default
  labels:
    app: m018-duration-1h-deadline-4h
    duration: duration-1h
    deadline: deadline-4h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m018
  template:
    metadata:
      labels:
        name: m018
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
---
