apiVersion: apps/v1
kind: Deployment
metadata:
  name: m068-duration-6h-deadline-9h
  namespace: default
  labels:
    app: m068-duration-6h-deadline-9h
    duration: duration-6h
    deadline: deadline-9h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m068
  template:
    metadata:
      labels:
        name: m068
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m069-duration-1h-deadline-7h
  namespace: default
  labels:
    app: m069-duration-1h-deadline-7h
    duration: duration-1h
    deadline: deadline-7h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m069
  template:
    metadata:
      labels:
        name: m069
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m070-duration-3h-deadline-4h
  namespace: default
  labels:
    app: m070-duration-3h-deadline-4h
    duration: duration-3h
    deadline: deadline-4h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m070
  template:
    metadata:
      labels:
        name: m070
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m071-duration-6h-deadline-7h
  namespace: default
  labels:
    app: m071-duration-6h-deadline-7h
    duration: duration-6h
    deadline: deadline-7h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m071
  template:
    metadata:
      labels:
        name: m071
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m072-duration-1h-deadline-2h
  namespace: default
  labels:
    app: m072-duration-1h-deadline-2h
    duration: duration-1h
    deadline: deadline-2h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m072
  template:
    metadata:
      labels:
        name: m072
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m073-duration-3h-deadline-6h
  namespace: default
  labels:
    app: m073-duration-3h-deadline-6h
    duration: duration-3h
    deadline: deadline-6h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m073
  template:
    metadata:
      labels:
        name: m073
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 100m
---
