apiVersion: apps/v1
kind: Deployment
metadata:
  name: m046-duration-3h-deadline-9h
  namespace: default
  labels:
    app: m046-duration-3h-deadline-9h
    duration: duration-3h
    deadline: deadline-9h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m046
  template:
    metadata:
      labels:
        name: m046
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
---
