apiVersion: apps/v1
kind: Deployment
metadata:
  name: m104-duration-6h-deadline-7h
  namespace: default
  labels:
    app: m104-duration-6h-deadline-7h
    duration: duration-6h
    deadline: deadline-7h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m104
  template:
    metadata:
      labels:
        name: m104
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 2000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m105-duration-1h-deadline-2h
  namespace: default
  labels:
    app: m105-duration-1h-deadline-2h
    duration: duration-1h
    deadline: deadline-2h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m105
  template:
    metadata:
      labels:
        name: m105
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m106-duration-3h-deadline-9h
  namespace: default
  labels:
    app: m106-duration-3h-deadline-9h
    duration: duration-3h
    deadline: deadline-9h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m106
  template:
    metadata:
      labels:
        name: m106
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m107-duration-6h-deadline-12h
  namespace: default
  labels:
    app: m107-duration-6h-deadline-12h
    duration: duration-6h
    deadline: deadline-12h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m107
  template:
    metadata:
      labels:
        name: m107
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 2Gi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m108-duration-1h-deadline-7h
  namespace: default
  labels:
    app: m108-duration-1h-deadline-7h
    duration: duration-1h
    deadline: deadline-7h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m108
  template:
    metadata:
      labels:
        name: m108
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 2000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m109-duration-3h-deadline-9h
  namespace: default
  labels:
    app: m109-duration-3h-deadline-9h
    duration: duration-3h
    deadline: deadline-9h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m109
  template:
    metadata:
      labels:
        name: m109
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m110-duration-6h-deadline-7h
  namespace: default
  labels:
    app: m110-duration-6h-deadline-7h
    duration: duration-6h
    deadline: deadline-7h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m110
  template:
    metadata:
      labels:
        name: m110
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m111-duration-1h-deadline-4h
  namespace: default
  labels:
    app: m111-duration-1h-deadline-4h
    duration: duration-1h
    deadline: deadline-4h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m111
  template:
    metadata:
      labels:
        name: m111
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m112-duration-3h-deadline-9h
  namespace: default
  labels:
    app: m112-duration-3h-deadline-9h
    duration: duration-3h
    deadline: deadline-9h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m112
  template:
    metadata:
      labels:
        name: m112
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m113-duration-6h-deadline-9h
  namespace: default
  labels:
    app: m113-duration-6h-deadline-9h
    duration: duration-6h
    deadline: deadline-9h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m113
  template:
    metadata:
      labels:
        name: m113
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 500m
---
