apiVersion: apps/v1
kind: Deployment
metadata:
  name: m050-duration-6h-deadline-12h
  namespace: default
  labels:
    app: m050-duration-6h-deadline-12h
    duration: duration-6h
    deadline: deadline-12h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m050
  template:
    metadata:
      labels:
        name: m050
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m051-duration-1h-deadline-7h
  namespace: default
  labels:
    app: m051-duration-1h-deadline-7h
    duration: duration-1h
    deadline: deadline-7h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m051
  template:
    metadata:
      labels:
        name: m051
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m052-duration-3h-deadline-9h
  namespace: default
  labels:
    app: m052-duration-3h-deadline-9h
    duration: duration-3h
    deadline: deadline-9h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m052
  template:
    metadata:
      labels:
        name: m052
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m053-duration-6h-deadline-9h
  namespace: default
  labels:
    app: m053-duration-6h-deadline-9h
    duration: duration-6h
    deadline: deadline-9h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m053
  template:
    metadata:
      labels:
        name: m053
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 100m
---
