apiVersion: apps/v1
kind: Deployment
metadata:
  name: m034-duration-3h-deadline-4h
  namespace: default
  labels:
    app: m034-duration-3h-deadline-4h
    duration: duration-3h
    deadline: deadline-4h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m034
  template:
    metadata:
      labels:
        name: m034
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m035-duration-6h-deadline-7h
  namespace: default
  labels:
    app: m035-duration-6h-deadline-7h
    duration: duration-6h
    deadline: deadline-7h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m035
  template:
    metadata:
      labels:
        name: m035
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m036-duration-1h-deadline-7h
  namespace: default
  labels:
    app: m036-duration-1h-deadline-7h
    duration: duration-1h
    deadline: deadline-7h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m036
  template:
    metadata:
      labels:
        name: m036
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m037-duration-3h-deadline-6h
  namespace: default
  labels:
    app: m037-duration-3h-deadline-6h
    duration: duration-3h
    deadline: deadline-6h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m037
  template:
    metadata:
      labels:
        name: m037
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m038-duration-6h-deadline-12h
  namespace: default
  labels:
    app: m038-duration-6h-deadline-12h
    duration: duration-6h
    deadline: deadline-12h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m038
  template:
    metadata:
      labels:
        name: m038
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
---
