apiVersion: apps/v1
kind: Deployment
metadata:
  name: m005-duration-6h-deadline-12h
  namespace: default
  labels:
    app: m005-duration-6h-deadline-12h
    duration: duration-6h
    deadline: deadline-12h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m005
  template:
    metadata:
      labels:
        name: m005
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m006-duration-1h-deadline-2h
  namespace: default
  labels:
    app: m006-duration-1h-deadline-2h
    duration: duration-1h
    deadline: deadline-2h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m006
  template:
    metadata:
      labels:
        name: m006
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m007-duration-3h-deadline-4h
  namespace: default
  labels:
    app: m007-duration-3h-deadline-4h
    duration: duration-3h
    deadline: deadline-4h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m007
  template:
    metadata:
      labels:
        name: m007
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m008-duration-6h-deadline-9h
  namespace: default
  labels:
    app: m008-duration-6h-deadline-9h
    duration: duration-6h
    deadline: deadline-9h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m008
  template:
    metadata:
      labels:
        name: m008
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 500m
---
