apiVersion: apps/v1
kind: Deployment
metadata:
  name: m198-duration-1h-deadline-3h
  namespace: default
  labels:
    app: m198-duration-1h-deadline-3h
    duration: duration-1h
    deadline: deadline-3h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m198
  template:
    metadata:
      labels:
        name: m198
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m199-duration-3h-deadline-27h
  namespace: default
  labels:
    app: m199-duration-3h-deadline-27h
    duration: duration-3h
    deadline: deadline-27h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m199
  template:
    metadata:
      labels:
        name: m199
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m200-duration-6h-deadline-30h
  namespace: default
  labels:
    app: m200-duration-6h-deadline-30h
    duration: duration-6h
    deadline: deadline-30h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m200
  template:
    metadata:
      labels:
        name: m200
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m201-duration-1h-deadline-3h
  namespace: default
  labels:
    app: m201-duration-1h-deadline-3h
    duration: duration-1h
    deadline: deadline-3h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m201
  template:
    metadata:
      labels:
        name: m201
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m202-duration-3h-deadline-9h
  namespace: default
  labels:
    app: m202-duration-3h-deadline-9h
    duration: duration-3h
    deadline: deadline-9h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m202
  template:
    metadata:
      labels:
        name: m202
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m203-duration-6h-deadline-12h
  namespace: default
  labels:
    app: m203-duration-6h-deadline-12h
    duration: duration-6h
    deadline: deadline-12h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m203
  template:
    metadata:
      labels:
        name: m203
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m204-duration-1h-deadline-25h
  namespace: default
  labels:
    app: m204-duration-1h-deadline-25h
    duration: duration-1h
    deadline: deadline-25h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m204
  template:
    metadata:
      labels:
        name: m204
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m205-duration-3h-deadline-27h
  namespace: default
  labels:
    app: m205-duration-3h-deadline-27h
    duration: duration-3h
    deadline: deadline-27h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m205
  template:
    metadata:
      labels:
        name: m205
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m206-duration-6h-deadline-30h
  namespace: default
  labels:
    app: m206-duration-6h-deadline-30h
    duration: duration-6h
    deadline: deadline-30h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m206
  template:
    metadata:
      labels:
        name: m206
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m207-duration-1h-deadline-25h
  namespace: default
  labels:
    app: m207-duration-1h-deadline-25h
    duration: duration-1h
    deadline: deadline-25h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m207
  template:
    metadata:
      labels:
        name: m207
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m208-duration-3h-deadline-27h
  namespace: default
  labels:
    app: m208-duration-3h-deadline-27h
    duration: duration-3h
    deadline: deadline-27h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m208
  template:
    metadata:
      labels:
        name: m208
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m209-duration-6h-deadline-8h
  namespace: default
  labels:
    app: m209-duration-6h-deadline-8h
    duration: duration-6h
    deadline: deadline-8h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m209
  template:
    metadata:
      labels:
        name: m209
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m210-duration-1h-deadline-7h
  namespace: default
  labels:
    app: m210-duration-1h-deadline-7h
    duration: duration-1h
    deadline: deadline-7h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m210
  template:
    metadata:
      labels:
        name: m210
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 250m
---
