apiVersion: apps/v1
kind: Deployment
metadata:
  name: m252-duration-1h-deadline-25h
  namespace: default
  labels:
    app: m252
    duration: duration-1h
    deadline: deadline-25h
  annotations:
    scheduling.carbon/duration_hours: '1'
    scheduling.carbon/deadline_hours: '25'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m252
  template:
    metadata:
      labels:
        name: m252
      annotations:
        scheduling.carbon/duration_hours: '1'
        scheduling.carbon/deadline_hours: '25'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m253-duration-3h-deadline-27h
  namespace: default
  labels:
    app: m253
    duration: duration-3h
    deadline: deadline-27h
  annotations:
    scheduling.carbon/duration_hours: '3'
    scheduling.carbon/deadline_hours: '27'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m253
  template:
    metadata:
      labels:
        name: m253
      annotations:
        scheduling.carbon/duration_hours: '3'
        scheduling.carbon/deadline_hours: '27'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m254-duration-6h-deadline-8h
  namespace: default
  labels:
    app: m254
    duration: duration-6h
    deadline: deadline-8h
  annotations:
    scheduling.carbon/duration_hours: '6'
    scheduling.carbon/deadline_hours: '8'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m254
  template:
    metadata:
      labels:
        name: m254
      annotations:
        scheduling.carbon/duration_hours: '6'
        scheduling.carbon/deadline_hours: '8'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m255-duration-1h-deadline-25h
  namespace: default
  labels:
    app: m255
    duration: duration-1h
    deadline: deadline-25h
  annotations:
    scheduling.carbon/duration_hours: '1'
    scheduling.carbon/deadline_hours: '25'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m255
  template:
    metadata:
      labels:
        name: m255
      annotations:
        scheduling.carbon/duration_hours: '1'
        scheduling.carbon/deadline_hours: '25'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m256-duration-3h-deadline-5h
  namespace: default
  labels:
    app: m256
    duration: duration-3h
    deadline: deadline-5h
  annotations:
    scheduling.carbon/duration_hours: '3'
    scheduling.carbon/deadline_hours: '5'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m256
  template:
    metadata:
      labels:
        name: m256
      annotations:
        scheduling.carbon/duration_hours: '3'
        scheduling.carbon/deadline_hours: '5'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m257-duration-6h-deadline-8h
  namespace: default
  labels:
    app: m257
    duration: duration-6h
    deadline: deadline-8h
  annotations:
    scheduling.carbon/duration_hours: '6'
    scheduling.carbon/deadline_hours: '8'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m257
  template:
    metadata:
      labels:
        name: m257
      annotations:
        scheduling.carbon/duration_hours: '6'
        scheduling.carbon/deadline_hours: '8'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m258-duration-1h-deadline-7h
  namespace: default
  labels:
    app: m258
    duration: duration-1h
    deadline: deadline-7h
  annotations:
    scheduling.carbon/duration_hours: '1'
    scheduling.carbon/deadline_hours: '7'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m258
  template:
    metadata:
      labels:
        name: m258
      annotations:
        scheduling.carbon/duration_hours: '1'
        scheduling.carbon/deadline_hours: '7'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m259-duration-3h-deadline-5h
  namespace: default
  labels:
    app: m259
    duration: duration-3h
    deadline: deadline-5h
  annotations:
    scheduling.carbon/duration_hours: '3'
    scheduling.carbon/deadline_hours: '5'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m259
  template:
    metadata:
      labels:
        name: m259
      annotations:
        scheduling.carbon/duration_hours: '3'
        scheduling.carbon/deadline_hours: '5'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m260-duration-6h-deadline-30h
  namespace: default
  labels:
    app: m260
    duration: duration-6h
    deadline: deadline-30h
  annotations:
    scheduling.carbon/duration_hours: '6'
    scheduling.carbon/deadline_hours: '30'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m260
  template:
    metadata:
      labels:
        name: m260
      annotations:
        scheduling.carbon/duration_hours: '6'
        scheduling.carbon/deadline_hours: '30'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m261-duration-1h-deadline-3h
  namespace: default
  labels:
    app: m261
    duration: duration-1h
    deadline: deadline-3h
  annotations:
    scheduling.carbon/duration_hours: '1'
    scheduling.carbon/deadline_hours: '3'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m261
  template:
    metadata:
      labels:
        name: m261
      annotations:
        scheduling.carbon/duration_hours: '1'
        scheduling.carbon/deadline_hours: '3'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m262-duration-3h-deadline-27h
  namespace: default
  labels:
    app: m262
    duration: duration-3h
    deadline: deadline-27h
  annotations:
    scheduling.carbon/duration_hours: '3'
    scheduling.carbon/deadline_hours: '27'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m262
  template:
    metadata:
      labels:
        name: m262
      annotations:
        scheduling.carbon/duration_hours: '3'
        scheduling.carbon/deadline_hours: '27'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m263-duration-6h-deadline-8h
  namespace: default
  labels:
    app: m263
    duration: duration-6h
    deadline: deadline-8h
  annotations:
    scheduling.carbon/duration_hours: '6'
    scheduling.carbon/deadline_hours: '8'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m263
  template:
    metadata:
      labels:
        name: m263
      annotations:
        scheduling.carbon/duration_hours: '6'
        scheduling.carbon/deadline_hours: '8'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m264-duration-1h-deadline-7h
  namespace: default
  labels:
    app: m264
    duration: duration-1h
    deadline: deadline-7h
  annotations:
    scheduling.carbon/duration_hours: '1'
    scheduling.carbon/deadline_hours: '7'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m264
  template:
    metadata:
      labels:
        name: m264
      annotations:
        scheduling.carbon/duration_hours: '1'
        scheduling.carbon/deadline_hours: '7'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m265-duration-3h-deadline-5h
  namespace: default
  labels:
    app: m265
    duration: duration-3h
    deadline: deadline-5h
  annotations:
    scheduling.carbon/duration_hours: '3'
    scheduling.carbon/deadline_hours: '5'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m265
  template:
    metadata:
      labels:
        name: m265
      annotations:
        scheduling.carbon/duration_hours: '3'
        scheduling.carbon/deadline_hours: '5'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
---
