apiVersion: apps/v1
kind: Deployment
metadata:
  name: m152
  namespace: default
  labels:
    app: m152
    duration: duration3
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m152
  template:
    metadata:
      labels:
        name: m152
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m153
  namespace: default
  labels:
    app: m153
    duration: duration1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m153
  template:
    metadata:
      labels:
        name: m153
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m154
  namespace: default
  labels:
    app: m154
    duration: duration1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m154
  template:
    metadata:
      labels:
        name: m154
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m155
  namespace: default
  labels:
    app: m155
    duration: duration1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m155
  template:
    metadata:
      labels:
        name: m155
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m156
  namespace: default
  labels:
    app: m156
    duration: duration3
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m156
  template:
    metadata:
      labels:
        name: m156
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m157
  namespace: default
  labels:
    app: m157
    duration: duration2
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m157
  template:
    metadata:
      labels:
        name: m157
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m158
  namespace: default
  labels:
    app: m158
    duration: duration2
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m158
  template:
    metadata:
      labels:
        name: m158
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m159
  namespace: default
  labels:
    app: m159
    duration: duration1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m159
  template:
    metadata:
      labels:
        name: m159
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m160
  namespace: default
  labels:
    app: m160
    duration: duration2
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m160
  template:
    metadata:
      labels:
        name: m160
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m161
  namespace: default
  labels:
    app: m161
    duration: duration3
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m161
  template:
    metadata:
      labels:
        name: m161
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m162
  namespace: default
  labels:
    app: m162
    duration: duration3
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m162
  template:
    metadata:
      labels:
        name: m162
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m163
  namespace: default
  labels:
    app: m163
    duration: duration2
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m163
  template:
    metadata:
      labels:
        name: m163
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
---
