apiVersion: apps/v1
kind: Deployment
metadata:
  name: m030-duration-1h-deadline-7h
  namespace: default
  labels:
    app: m030
    duration: duration-1h
    deadline: deadline-7h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m030
  template:
    metadata:
      labels:
        name: m030
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m031-duration-3h-deadline-27h
  namespace: default
  labels:
    app: m031
    duration: duration-3h
    deadline: deadline-27h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m031
  template:
    metadata:
      labels:
        name: m031
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m032-duration-6h-deadline-30h
  namespace: default
  labels:
    app: m032
    duration: duration-6h
    deadline: deadline-30h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m032
  template:
    metadata:
      labels:
        name: m032
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m033-duration-1h-deadline-3h
  namespace: default
  labels:
    app: m033
    duration: duration-1h
    deadline: deadline-3h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m033
  template:
    metadata:
      labels:
        name: m033
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m034-duration-3h-deadline-5h
  namespace: default
  labels:
    app: m034
    duration: duration-3h
    deadline: deadline-5h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m034
  template:
    metadata:
      labels:
        name: m034
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m035-duration-6h-deadline-8h
  namespace: default
  labels:
    app: m035
    duration: duration-6h
    deadline: deadline-8h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m035
  template:
    metadata:
      labels:
        name: m035
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m036-duration-1h-deadline-25h
  namespace: default
  labels:
    app: m036
    duration: duration-1h
    deadline: deadline-25h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m036
  template:
    metadata:
      labels:
        name: m036
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m037-duration-3h-deadline-9h
  namespace: default
  labels:
    app: m037
    duration: duration-3h
    deadline: deadline-9h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m037
  template:
    metadata:
      labels:
        name: m037
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m038-duration-6h-deadline-30h
  namespace: default
  labels:
    app: m038
    duration: duration-6h
    deadline: deadline-30h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m038
  template:
    metadata:
      labels:
        name: m038
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m039-duration-1h-deadline-25h
  namespace: default
  labels:
    app: m039
    duration: duration-1h
    deadline: deadline-25h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m039
  template:
    metadata:
      labels:
        name: m039
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m040-duration-3h-deadline-5h
  namespace: default
  labels:
    app: m040
    duration: duration-3h
    deadline: deadline-5h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m040
  template:
    metadata:
      labels:
        name: m040
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m041-duration-6h-deadline-8h
  namespace: default
  labels:
    app: m041
    duration: duration-6h
    deadline: deadline-8h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m041
  template:
    metadata:
      labels:
        name: m041
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m042-duration-1h-deadline-25h
  namespace: default
  labels:
    app: m042
    duration: duration-1h
    deadline: deadline-25h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m042
  template:
    metadata:
      labels:
        name: m042
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m043-duration-3h-deadline-27h
  namespace: default
  labels:
    app: m043
    duration: duration-3h
    deadline: deadline-27h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m043
  template:
    metadata:
      labels:
        name: m043
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m044-duration-6h-deadline-30h
  namespace: default
  labels:
    app: m044
    duration: duration-6h
    deadline: deadline-30h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m044
  template:
    metadata:
      labels:
        name: m044
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m045-duration-1h-deadline-7h
  namespace: default
  labels:
    app: m045
    duration: duration-1h
    deadline: deadline-7h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m045
  template:
    metadata:
      labels:
        name: m045
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m046-duration-3h-deadline-27h
  namespace: default
  labels:
    app: m046
    duration: duration-3h
    deadline: deadline-27h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m046
  template:
    metadata:
      labels:
        name: m046
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
---
