apiVersion: apps/v1
kind: Deployment
metadata:
  name: m124
  namespace: default
  labels:
    app: m124
    duration: duration1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m124
  template:
    metadata:
      labels:
        name: m124
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m125
  namespace: default
  labels:
    app: m125
    duration: duration1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m125
  template:
    metadata:
      labels:
        name: m125
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m126
  namespace: default
  labels:
    app: m126
    duration: duration2
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m126
  template:
    metadata:
      labels:
        name: m126
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m127
  namespace: default
  labels:
    app: m127
    duration: duration1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m127
  template:
    metadata:
      labels:
        name: m127
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m128
  namespace: default
  labels:
    app: m128
    duration: duration2
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m128
  template:
    metadata:
      labels:
        name: m128
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m129
  namespace: default
  labels:
    app: m129
    duration: duration2
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m129
  template:
    metadata:
      labels:
        name: m129
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m130
  namespace: default
  labels:
    app: m130
    duration: duration3
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m130
  template:
    metadata:
      labels:
        name: m130
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m131
  namespace: default
  labels:
    app: m131
    duration: duration1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m131
  template:
    metadata:
      labels:
        name: m131
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m132
  namespace: default
  labels:
    app: m132
    duration: duration3
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m132
  template:
    metadata:
      labels:
        name: m132
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m133
  namespace: default
  labels:
    app: m133
    duration: duration1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m133
  template:
    metadata:
      labels:
        name: m133
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m134
  namespace: default
  labels:
    app: m134
    duration: duration3
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m134
  template:
    metadata:
      labels:
        name: m134
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m135
  namespace: default
  labels:
    app: m135
    duration: duration3
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m135
  template:
    metadata:
      labels:
        name: m135
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m136
  namespace: default
  labels:
    app: m136
    duration: duration3
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m136
  template:
    metadata:
      labels:
        name: m136
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 1000m
---
