apiVersion: apps/v1
kind: Deployment
metadata:
  name: m164
  namespace: default
  labels:
    app: m164
    duration: duration3
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m164
  template:
    metadata:
      labels:
        name: m164
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m165
  namespace: default
  labels:
    app: m165
    duration: duration3
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m165
  template:
    metadata:
      labels:
        name: m165
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m166
  namespace: default
  labels:
    app: m166
    duration: duration1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m166
  template:
    metadata:
      labels:
        name: m166
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m167
  namespace: default
  labels:
    app: m167
    duration: duration2
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m167
  template:
    metadata:
      labels:
        name: m167
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m168
  namespace: default
  labels:
    app: m168
    duration: duration3
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m168
  template:
    metadata:
      labels:
        name: m168
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m169
  namespace: default
  labels:
    app: m169
    duration: duration2
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m169
  template:
    metadata:
      labels:
        name: m169
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m170
  namespace: default
  labels:
    app: m170
    duration: duration3
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m170
  template:
    metadata:
      labels:
        name: m170
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m171
  namespace: default
  labels:
    app: m171
    duration: duration2
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m171
  template:
    metadata:
      labels:
        name: m171
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m172
  namespace: default
  labels:
    app: m172
    duration: duration3
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m172
  template:
    metadata:
      labels:
        name: m172
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m173
  namespace: default
  labels:
    app: m173
    duration: duration1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m173
  template:
    metadata:
      labels:
        name: m173
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m174
  namespace: default
  labels:
    app: m174
    duration: duration3
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m174
  template:
    metadata:
      labels:
        name: m174
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m175
  namespace: default
  labels:
    app: m175
    duration: duration1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m175
  template:
    metadata:
      labels:
        name: m175
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m176
  namespace: default
  labels:
    app: m176
    duration: duration2
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m176
  template:
    metadata:
      labels:
        name: m176
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m177
  namespace: default
  labels:
    app: m177
    duration: duration1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m177
  template:
    metadata:
      labels:
        name: m177
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m178
  namespace: default
  labels:
    app: m178
    duration: duration2
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m178
  template:
    metadata:
      labels:
        name: m178
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m179
  namespace: default
  labels:
    app: m179
    duration: duration2
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m179
  template:
    metadata:
      labels:
        name: m179
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m180
  namespace: default
  labels:
    app: m180
    duration: duration2
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m180
  template:
    metadata:
      labels:
        name: m180
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 1000m
---
