apiVersion: apps/v1
kind: Deployment
metadata:
  name: m211-duration-3h-deadline-9h
  namespace: default
  labels:
    app: m211
    duration: duration-3h
    deadline: deadline-9h
  annotations:
    scheduling.carbon/duration_hours: '3'
    scheduling.carbon/deadline_hours: '9'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m211
  template:
    metadata:
      labels:
        name: m211
      annotations:
        scheduling.carbon/duration_hours: '3'
        scheduling.carbon/deadline_hours: '9'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m212-duration-6h-deadline-30h
  namespace: default
  labels:
    app: m212
    duration: duration-6h
    deadline: deadline-30h
  annotations:
    scheduling.carbon/duration_hours: '6'
    scheduling.carbon/deadline_hours: '30'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m212
  template:
    metadata:
      labels:
        name: m212
      annotations:
        scheduling.carbon/duration_hours: '6'
        scheduling.carbon/deadline_hours: '30'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m213-duration-1h-deadline-3h
  namespace: default
  labels:
    app: m213
    duration: duration-1h
    deadline: deadline-3h
  annotations:
    scheduling.carbon/duration_hours: '1'
    scheduling.carbon/deadline_hours: '3'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m213
  template:
    metadata:
      labels:
        name: m213
      annotations:
        scheduling.carbon/duration_hours: '1'
        scheduling.carbon/deadline_hours: '3'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m214-duration-3h-deadline-9h
  namespace: default
  labels:
    app: m214
    duration: duration-3h
    deadline: deadline-9h
  annotations:
    scheduling.carbon/duration_hours: '3'
    scheduling.carbon/deadline_hours: '9'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m214
  template:
    metadata:
      labels:
        name: m214
      annotations:
        scheduling.carbon/duration_hours: '3'
        scheduling.carbon/deadline_hours: '9'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m215-duration-6h-deadline-12h
  namespace: default
  labels:
    app: m215
    duration: duration-6h
    deadline: deadline-12h
  annotations:
    scheduling.carbon/duration_hours: '6'
    scheduling.carbon/deadline_hours: '12'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m215
  template:
    metadata:
      labels:
        name: m215
      annotations:
        scheduling.carbon/duration_hours: '6'
        scheduling.carbon/deadline_hours: '12'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m216-duration-1h-deadline-7h
  namespace: default
  labels:
    app: m216
    duration: duration-1h
    deadline: deadline-7h
  annotations:
    scheduling.carbon/duration_hours: '1'
    scheduling.carbon/deadline_hours: '7'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m216
  template:
    metadata:
      labels:
        name: m216
      annotations:
        scheduling.carbon/duration_hours: '1'
        scheduling.carbon/deadline_hours: '7'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m217-duration-3h-deadline-9h
  namespace: default
  labels:
    app: m217
    duration: duration-3h
    deadline: deadline-9h
  annotations:
    scheduling.carbon/duration_hours: '3'
    scheduling.carbon/deadline_hours: '9'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m217
  template:
    metadata:
      labels:
        name: m217
      annotations:
        scheduling.carbon/duration_hours: '3'
        scheduling.carbon/deadline_hours: '9'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m218-duration-6h-deadline-8h
  namespace: default
  labels:
    app: m218
    duration: duration-6h
    deadline: deadline-8h
  annotations:
    scheduling.carbon/duration_hours: '6'
    scheduling.carbon/deadline_hours: '8'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m218
  template:
    metadata:
      labels:
        name: m218
      annotations:
        scheduling.carbon/duration_hours: '6'
        scheduling.carbon/deadline_hours: '8'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m219-duration-1h-deadline-3h
  namespace: default
  labels:
    app: m219
    duration: duration-1h
    deadline: deadline-3h
  annotations:
    scheduling.carbon/duration_hours: '1'
    scheduling.carbon/deadline_hours: '3'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m219
  template:
    metadata:
      labels:
        name: m219
      annotations:
        scheduling.carbon/duration_hours: '1'
        scheduling.carbon/deadline_hours: '3'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m220-duration-3h-deadline-9h
  namespace: default
  labels:
    app: m220
    duration: duration-3h
    deadline: deadline-9h
  annotations:
    scheduling.carbon/duration_hours: '3'
    scheduling.carbon/deadline_hours: '9'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m220
  template:
    metadata:
      labels:
        name: m220
      annotations:
        scheduling.carbon/duration_hours: '3'
        scheduling.carbon/deadline_hours: '9'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m221-duration-6h-deadline-12h
  namespace: default
  labels:
    app: m221
    duration: duration-6h
    deadline: deadline-12h
  annotations:
    scheduling.carbon/duration_hours: '6'
    scheduling.carbon/deadline_hours: '12'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m221
  template:
    metadata:
      labels:
        name: m221
      annotations:
        scheduling.carbon/duration_hours: '6'
        scheduling.carbon/deadline_hours: '12'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m222-duration-1h-deadline-25h
  namespace: default
  labels:
    app: m222
    duration: duration-1h
    deadline: deadline-25h
  annotations:
    scheduling.carbon/duration_hours: '1'
    scheduling.carbon/deadline_hours: '25'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m222
  template:
    metadata:
      labels:
        name: m222
      annotations:
        scheduling.carbon/duration_hours: '1'
        scheduling.carbon/deadline_hours: '25'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m223-duration-3h-deadline-5h
  namespace: default
  labels:
    app: m223
    duration: duration-3h
    deadline: deadline-5h
  annotations:
    scheduling.carbon/duration_hours: '3'
    scheduling.carbon/deadline_hours: '5'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m223
  template:
    metadata:
      labels:
        name: m223
      annotations:
        scheduling.carbon/duration_hours: '3'
        scheduling.carbon/deadline_hours: '5'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m224-duration-6h-deadline-30h
  namespace: default
  labels:
    app: m224
    duration: duration-6h
    deadline: deadline-30h
  annotations:
    scheduling.carbon/duration_hours: '6'
    scheduling.carbon/deadline_hours: '30'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m224
  template:
    metadata:
      labels:
        name: m224
      annotations:
        scheduling.carbon/duration_hours: '6'
        scheduling.carbon/deadline_hours: '30'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m225-duration-1h-deadline-25h
  namespace: default
  labels:
    app: m225
    duration: duration-1h
    deadline: deadline-25h
  annotations:
    scheduling.carbon/duration_hours: '1'
    scheduling.carbon/deadline_hours: '25'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m225
  template:
    metadata:
      labels:
        name: m225
      annotations:
        scheduling.carbon/duration_hours: '1'
        scheduling.carbon/deadline_hours: '25'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m226-duration-3h-deadline-5h
  namespace: default
  labels:
    app: m226
    duration: duration-3h
    deadline: deadline-5h
  annotations:
    scheduling.carbon/duration_hours: '3'
    scheduling.carbon/deadline_hours: '5'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m226
  template:
    metadata:
      labels:
        name: m226
      annotations:
        scheduling.carbon/duration_hours: '3'
        scheduling.carbon/deadline_hours: '5'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m227-duration-6h-deadline-8h
  namespace: default
  labels:
    app: m227
    duration: duration-6h
    deadline: deadline-8h
  annotations:
    scheduling.carbon/duration_hours: '6'
    scheduling.carbon/deadline_hours: '8'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m227
  template:
    metadata:
      labels:
        name: m227
      annotations:
        scheduling.carbon/duration_hours: '6'
        scheduling.carbon/deadline_hours: '8'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m228-duration-1h-deadline-7h
  namespace: default
  labels:
    app: m228
    duration: duration-1h
    deadline: deadline-7h
  annotations:
    scheduling.carbon/duration_hours: '1'
    scheduling.carbon/deadline_hours: '7'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m228
  template:
    metadata:
      labels:
        name: m228
      annotations:
        scheduling.carbon/duration_hours: '1'
        scheduling.carbon/deadline_hours: '7'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 100m
---
