apiVersion: apps/v1
kind: Deployment
metadata:
  name: m229-duration-3h-deadline-27h
  namespace: default
  labels:
    app: m229
    duration: duration-3h
    deadline: deadline-27h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m229
  template:
    metadata:
      labels:
        name: m229
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m230-duration-6h-deadline-30h
  namespace: default
  labels:
    app: m230
    duration: duration-6h
    deadline: deadline-30h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m230
  template:
    metadata:
      labels:
        name: m230
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m231-duration-1h-deadline-25h
  namespace: default
  labels:
    app: m231
    duration: duration-1h
    deadline: deadline-25h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m231
  template:
    metadata:
      labels:
        name: m231
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m232-duration-3h-deadline-9h
  namespace: default
  labels:
    app: m232
    duration: duration-3h
    deadline: deadline-9h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m232
  template:
    metadata:
      labels:
        name: m232
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m233-duration-6h-deadline-8h
  namespace: default
  labels:
    app: m233
    duration: duration-6h
    deadline: deadline-8h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m233
  template:
    metadata:
      labels:
        name: m233
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m234-duration-1h-deadline-3h
  namespace: default
  labels:
    app: m234
    duration: duration-1h
    deadline: deadline-3h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m234
  template:
    metadata:
      labels:
        name: m234
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m235-duration-3h-deadline-5h
  namespace: default
  labels:
    app: m235
    duration: duration-3h
    deadline: deadline-5h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m235
  template:
    metadata:
      labels:
        name: m235
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m236-duration-6h-deadline-30h
  namespace: default
  labels:
    app: m236
    duration: duration-6h
    deadline: deadline-30h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m236
  template:
    metadata:
      labels:
        name: m236
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m237-duration-1h-deadline-3h
  namespace: default
  labels:
    app: m237
    duration: duration-1h
    deadline: deadline-3h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m237
  template:
    metadata:
      labels:
        name: m237
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m238-duration-3h-deadline-9h
  namespace: default
  labels:
    app: m238
    duration: duration-3h
    deadline: deadline-9h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m238
  template:
    metadata:
      labels:
        name: m238
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 250m
---
