apiVersion: apps/v1
kind: Deployment
metadata:
  name: m298-duration-3h-deadline-9h
  namespace: default
  labels:
    app: m298
    duration: duration-3h
    deadline: deadline-9h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m298
  template:
    metadata:
      labels:
        name: m298
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m299-duration-6h-deadline-8h
  namespace: default
  labels:
    app: m299
    duration: duration-6h
    deadline: deadline-8h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m299
  template:
    metadata:
      labels:
        name: m299
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m300-duration-1h-deadline-7h
  namespace: default
  labels:
    app: m300
    duration: duration-1h
    deadline: deadline-7h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m300
  template:
    metadata:
      labels:
        name: m300
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m301-duration-3h-deadline-9h
  namespace: default
  labels:
    app: m301
    duration: duration-3h
    deadline: deadline-9h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m301
  template:
    metadata:
      labels:
        name: m301
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m302-duration-6h-deadline-8h
  namespace: default
  labels:
    app: m302
    duration: duration-6h
    deadline: deadline-8h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m302
  template:
    metadata:
      labels:
        name: m302
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m303-duration-1h-deadline-7h
  namespace: default
  labels:
    app: m303
    duration: duration-1h
    deadline: deadline-7h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m303
  template:
    metadata:
      labels:
        name: m303
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m304-duration-3h-deadline-9h
  namespace: default
  labels:
    app: m304
    duration: duration-3h
    deadline: deadline-9h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m304
  template:
    metadata:
      labels:
        name: m304
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m305-duration-6h-deadline-30h
  namespace: default
  labels:
    app: m305
    duration: duration-6h
    deadline: deadline-30h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m305
  template:
    metadata:
      labels:
        name: m305
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m306-duration-1h-deadline-3h
  namespace: default
  labels:
    app: m306
    duration: duration-1h
    deadline: deadline-3h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m306
  template:
    metadata:
      labels:
        name: m306
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m307-duration-3h-deadline-9h
  namespace: default
  labels:
    app: m307
    duration: duration-3h
    deadline: deadline-9h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m307
  template:
    metadata:
      labels:
        name: m307
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m308-duration-6h-deadline-12h
  namespace: default
  labels:
    app: m308
    duration: duration-6h
    deadline: deadline-12h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m308
  template:
    metadata:
      labels:
        name: m308
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m309-duration-1h-deadline-3h
  namespace: default
  labels:
    app: m309
    duration: duration-1h
    deadline: deadline-3h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m309
  template:
    metadata:
      labels:
        name: m309
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m310-duration-3h-deadline-5h
  namespace: default
  labels:
    app: m310
    duration: duration-3h
    deadline: deadline-5h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m310
  template:
    metadata:
      labels:
        name: m310
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m311-duration-6h-deadline-30h
  namespace: default
  labels:
    app: m311
    duration: duration-6h
    deadline: deadline-30h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m311
  template:
    metadata:
      labels:
        name: m311
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m312-duration-1h-deadline-25h
  namespace: default
  labels:
    app: m312
    duration: duration-1h
    deadline: deadline-25h
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m312
  template:
    metadata:
      labels:
        name: m312
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 100m
---
