apiVersion: apps/v1
kind: Deployment
metadata:
  name: m152-duration-6h-deadline-30h
  namespace: default
  labels:
    app: m152
    duration: duration-6h
    deadline: deadline-30h
  annotations:
    scheduling.carbon/duration_hours: '6'
    scheduling.carbon/deadline_hours: '30'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m152
  template:
    metadata:
      labels:
        name: m152
      annotations:
        scheduling.carbon/duration_hours: '6'
        scheduling.carbon/deadline_hours: '30'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m153-duration-1h-deadline-3h
  namespace: default
  labels:
    app: m153
    duration: duration-1h
    deadline: deadline-3h
  annotations:
    scheduling.carbon/duration_hours: '1'
    scheduling.carbon/deadline_hours: '3'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m153
  template:
    metadata:
      labels:
        name: m153
      annotations:
        scheduling.carbon/duration_hours: '1'
        scheduling.carbon/deadline_hours: '3'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m154-duration-3h-deadline-5h
  namespace: default
  labels:
    app: m154
    duration: duration-3h
    deadline: deadline-5h
  annotations:
    scheduling.carbon/duration_hours: '3'
    scheduling.carbon/deadline_hours: '5'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m154
  template:
    metadata:
      labels:
        name: m154
      annotations:
        scheduling.carbon/duration_hours: '3'
        scheduling.carbon/deadline_hours: '5'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m155-duration-6h-deadline-8h
  namespace: default
  labels:
    app: m155
    duration: duration-6h
    deadline: deadline-8h
  annotations:
    scheduling.carbon/duration_hours: '6'
    scheduling.carbon/deadline_hours: '8'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m155
  template:
    metadata:
      labels:
        name: m155
      annotations:
        scheduling.carbon/duration_hours: '6'
        scheduling.carbon/deadline_hours: '8'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m156-duration-1h-deadline-25h
  namespace: default
  labels:
    app: m156
    duration: duration-1h
    deadline: deadline-25h
  annotations:
    scheduling.carbon/duration_hours: '1'
    scheduling.carbon/deadline_hours: '25'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m156
  template:
    metadata:
      labels:
        name: m156
      annotations:
        scheduling.carbon/duration_hours: '1'
        scheduling.carbon/deadline_hours: '25'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m157-duration-3h-deadline-9h
  namespace: default
  labels:
    app: m157
    duration: duration-3h
    deadline: deadline-9h
  annotations:
    scheduling.carbon/duration_hours: '3'
    scheduling.carbon/deadline_hours: '9'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m157
  template:
    metadata:
      labels:
        name: m157
      annotations:
        scheduling.carbon/duration_hours: '3'
        scheduling.carbon/deadline_hours: '9'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m158-duration-6h-deadline-12h
  namespace: default
  labels:
    app: m158
    duration: duration-6h
    deadline: deadline-12h
  annotations:
    scheduling.carbon/duration_hours: '6'
    scheduling.carbon/deadline_hours: '12'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m158
  template:
    metadata:
      labels:
        name: m158
      annotations:
        scheduling.carbon/duration_hours: '6'
        scheduling.carbon/deadline_hours: '12'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m159-duration-1h-deadline-3h
  namespace: default
  labels:
    app: m159
    duration: duration-1h
    deadline: deadline-3h
  annotations:
    scheduling.carbon/duration_hours: '1'
    scheduling.carbon/deadline_hours: '3'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m159
  template:
    metadata:
      labels:
        name: m159
      annotations:
        scheduling.carbon/duration_hours: '1'
        scheduling.carbon/deadline_hours: '3'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m160-duration-3h-deadline-9h
  namespace: default
  labels:
    app: m160
    duration: duration-3h
    deadline: deadline-9h
  annotations:
    scheduling.carbon/duration_hours: '3'
    scheduling.carbon/deadline_hours: '9'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m160
  template:
    metadata:
      labels:
        name: m160
      annotations:
        scheduling.carbon/duration_hours: '3'
        scheduling.carbon/deadline_hours: '9'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m161-duration-6h-deadline-30h
  namespace: default
  labels:
    app: m161
    duration: duration-6h
    deadline: deadline-30h
  annotations:
    scheduling.carbon/duration_hours: '6'
    scheduling.carbon/deadline_hours: '30'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m161
  template:
    metadata:
      labels:
        name: m161
      annotations:
        scheduling.carbon/duration_hours: '6'
        scheduling.carbon/deadline_hours: '30'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m162-duration-1h-deadline-25h
  namespace: default
  labels:
    app: m162
    duration: duration-1h
    deadline: deadline-25h
  annotations:
    scheduling.carbon/duration_hours: '1'
    scheduling.carbon/deadline_hours: '25'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m162
  template:
    metadata:
      labels:
        name: m162
      annotations:
        scheduling.carbon/duration_hours: '1'
        scheduling.carbon/deadline_hours: '25'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m163-duration-3h-deadline-9h
  namespace: default
  labels:
    app: m163
    duration: duration-3h
    deadline: deadline-9h
  annotations:
    scheduling.carbon/duration_hours: '3'
    scheduling.carbon/deadline_hours: '9'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m163
  template:
    metadata:
      labels:
        name: m163
      annotations:
        scheduling.carbon/duration_hours: '3'
        scheduling.carbon/deadline_hours: '9'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
---
