apiVersion: apps/v1
kind: Deployment
metadata:
  name: m107
  namespace: default
  labels:
    app: m107
    duration: duration2
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m107
  template:
    metadata:
      labels:
        name: m107
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m108
  namespace: default
  labels:
    app: m108
    duration: duration3
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m108
  template:
    metadata:
      labels:
        name: m108
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m109
  namespace: default
  labels:
    app: m109
    duration: duration1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m109
  template:
    metadata:
      labels:
        name: m109
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m110
  namespace: default
  labels:
    app: m110
    duration: duration1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m110
  template:
    metadata:
      labels:
        name: m110
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m111
  namespace: default
  labels:
    app: m111
    duration: duration3
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m111
  template:
    metadata:
      labels:
        name: m111
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m112
  namespace: default
  labels:
    app: m112
    duration: duration3
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m112
  template:
    metadata:
      labels:
        name: m112
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m113
  namespace: default
  labels:
    app: m113
    duration: duration1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m113
  template:
    metadata:
      labels:
        name: m113
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m114
  namespace: default
  labels:
    app: m114
    duration: duration2
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m114
  template:
    metadata:
      labels:
        name: m114
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m115
  namespace: default
  labels:
    app: m115
    duration: duration1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m115
  template:
    metadata:
      labels:
        name: m115
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m116
  namespace: default
  labels:
    app: m116
    duration: duration2
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m116
  template:
    metadata:
      labels:
        name: m116
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m117
  namespace: default
  labels:
    app: m117
    duration: duration1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m117
  template:
    metadata:
      labels:
        name: m117
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m118
  namespace: default
  labels:
    app: m118
    duration: duration2
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m118
  template:
    metadata:
      labels:
        name: m118
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m119
  namespace: default
  labels:
    app: m119
    duration: duration1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m119
  template:
    metadata:
      labels:
        name: m119
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m120
  namespace: default
  labels:
    app: m120
    duration: duration2
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m120
  template:
    metadata:
      labels:
        name: m120
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m121
  namespace: default
  labels:
    app: m121
    duration: duration3
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m121
  template:
    metadata:
      labels:
        name: m121
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m122
  namespace: default
  labels:
    app: m122
    duration: duration3
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m122
  template:
    metadata:
      labels:
        name: m122
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m123
  namespace: default
  labels:
    app: m123
    duration: duration1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m123
  template:
    metadata:
      labels:
        name: m123
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 500m
---
