apiVersion: apps/v1
kind: Deployment
metadata:
  name: m239-duration-6h-deadline-8h
  namespace: default
  labels:
    app: m239
    duration: duration-6h
    deadline: deadline-8h
  annotations:
    scheduling.carbon/duration_hours: '6'
    scheduling.carbon/deadline_hours: '8'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m239
  template:
    metadata:
      labels:
        name: m239
      annotations:
        scheduling.carbon/duration_hours: '6'
        scheduling.carbon/deadline_hours: '8'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m240-duration-1h-deadline-3h
  namespace: default
  labels:
    app: m240
    duration: duration-1h
    deadline: deadline-3h
  annotations:
    scheduling.carbon/duration_hours: '1'
    scheduling.carbon/deadline_hours: '3'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m240
  template:
    metadata:
      labels:
        name: m240
      annotations:
        scheduling.carbon/duration_hours: '1'
        scheduling.carbon/deadline_hours: '3'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m241-duration-3h-deadline-27h
  namespace: default
  labels:
    app: m241
    duration: duration-3h
    deadline: deadline-27h
  annotations:
    scheduling.carbon/duration_hours: '3'
    scheduling.carbon/deadline_hours: '27'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m241
  template:
    metadata:
      labels:
        name: m241
      annotations:
        scheduling.carbon/duration_hours: '3'
        scheduling.carbon/deadline_hours: '27'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m242-duration-6h-deadline-8h
  namespace: default
  labels:
    app: m242
    duration: duration-6h
    deadline: deadline-8h
  annotations:
    scheduling.carbon/duration_hours: '6'
    scheduling.carbon/deadline_hours: '8'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m242
  template:
    metadata:
      labels:
        name: m242
      annotations:
        scheduling.carbon/duration_hours: '6'
        scheduling.carbon/deadline_hours: '8'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m243-duration-1h-deadline-7h
  namespace: default
  labels:
    app: m243
    duration: duration-1h
    deadline: deadline-7h
  annotations:
    scheduling.carbon/duration_hours: '1'
    scheduling.carbon/deadline_hours: '7'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m243
  template:
    metadata:
      labels:
        name: m243
      annotations:
        scheduling.carbon/duration_hours: '1'
        scheduling.carbon/deadline_hours: '7'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m244-duration-3h-deadline-9h
  namespace: default
  labels:
    app: m244
    duration: duration-3h
    deadline: deadline-9h
  annotations:
    scheduling.carbon/duration_hours: '3'
    scheduling.carbon/deadline_hours: '9'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m244
  template:
    metadata:
      labels:
        name: m244
      annotations:
        scheduling.carbon/duration_hours: '3'
        scheduling.carbon/deadline_hours: '9'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m245-duration-6h-deadline-12h
  namespace: default
  labels:
    app: m245
    duration: duration-6h
    deadline: deadline-12h
  annotations:
    scheduling.carbon/duration_hours: '6'
    scheduling.carbon/deadline_hours: '12'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m245
  template:
    metadata:
      labels:
        name: m245
      annotations:
        scheduling.carbon/duration_hours: '6'
        scheduling.carbon/deadline_hours: '12'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m246-duration-1h-deadline-3h
  namespace: default
  labels:
    app: m246
    duration: duration-1h
    deadline: deadline-3h
  annotations:
    scheduling.carbon/duration_hours: '1'
    scheduling.carbon/deadline_hours: '3'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m246
  template:
    metadata:
      labels:
        name: m246
      annotations:
        scheduling.carbon/duration_hours: '1'
        scheduling.carbon/deadline_hours: '3'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m247-duration-3h-deadline-5h
  namespace: default
  labels:
    app: m247
    duration: duration-3h
    deadline: deadline-5h
  annotations:
    scheduling.carbon/duration_hours: '3'
    scheduling.carbon/deadline_hours: '5'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m247
  template:
    metadata:
      labels:
        name: m247
      annotations:
        scheduling.carbon/duration_hours: '3'
        scheduling.carbon/deadline_hours: '5'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m248-duration-6h-deadline-8h
  namespace: default
  labels:
    app: m248
    duration: duration-6h
    deadline: deadline-8h
  annotations:
    scheduling.carbon/duration_hours: '6'
    scheduling.carbon/deadline_hours: '8'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m248
  template:
    metadata:
      labels:
        name: m248
      annotations:
        scheduling.carbon/duration_hours: '6'
        scheduling.carbon/deadline_hours: '8'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m249-duration-1h-deadline-3h
  namespace: default
  labels:
    app: m249
    duration: duration-1h
    deadline: deadline-3h
  annotations:
    scheduling.carbon/duration_hours: '1'
    scheduling.carbon/deadline_hours: '3'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m249
  template:
    metadata:
      labels:
        name: m249
      annotations:
        scheduling.carbon/duration_hours: '1'
        scheduling.carbon/deadline_hours: '3'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m250-duration-3h-deadline-27h
  namespace: default
  labels:
    app: m250
    duration: duration-3h
    deadline: deadline-27h
  annotations:
    scheduling.carbon/duration_hours: '3'
    scheduling.carbon/deadline_hours: '27'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m250
  template:
    metadata:
      labels:
        name: m250
      annotations:
        scheduling.carbon/duration_hours: '3'
        scheduling.carbon/deadline_hours: '27'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m251-duration-6h-deadline-12h
  namespace: default
  labels:
    app: m251
    duration: duration-6h
    deadline: deadline-12h
  annotations:
    scheduling.carbon/duration_hours: '6'
    scheduling.carbon/deadline_hours: '12'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m251
  template:
    metadata:
      labels:
        name: m251
      annotations:
        scheduling.carbon/duration_hours: '6'
        scheduling.carbon/deadline_hours: '12'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 500m
---
