apiVersion: apps/v1
kind: Deployment
metadata:
  name: m107-duration-6h-deadline-12h
  namespace: default
  labels:
    app: m107
    duration: duration-6h
    deadline: deadline-12h
  annotations:
    scheduling.carbon/duration_hours: '6'
    scheduling.carbon/deadline_hours: '12'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m107
  template:
    metadata:
      labels:
        name: m107
      annotations:
        scheduling.carbon/duration_hours: '6'
        scheduling.carbon/deadline_hours: '12'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m108-duration-1h-deadline-25h
  namespace: default
  labels:
    app: m108
    duration: duration-1h
    deadline: deadline-25h
  annotations:
    scheduling.carbon/duration_hours: '1'
    scheduling.carbon/deadline_hours: '25'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m108
  template:
    metadata:
      labels:
        name: m108
      annotations:
        scheduling.carbon/duration_hours: '1'
        scheduling.carbon/deadline_hours: '25'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m109-duration-3h-deadline-5h
  namespace: default
  labels:
    app: m109
    duration: duration-3h
    deadline: deadline-5h
  annotations:
    scheduling.carbon/duration_hours: '3'
    scheduling.carbon/deadline_hours: '5'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m109
  template:
    metadata:
      labels:
        name: m109
      annotations:
        scheduling.carbon/duration_hours: '3'
        scheduling.carbon/deadline_hours: '5'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m110-duration-6h-deadline-8h
  namespace: default
  labels:
    app: m110
    duration: duration-6h
    deadline: deadline-8h
  annotations:
    scheduling.carbon/duration_hours: '6'
    scheduling.carbon/deadline_hours: '8'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m110
  template:
    metadata:
      labels:
        name: m110
      annotations:
        scheduling.carbon/duration_hours: '6'
        scheduling.carbon/deadline_hours: '8'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m111-duration-1h-deadline-25h
  namespace: default
  labels:
    app: m111
    duration: duration-1h
    deadline: deadline-25h
  annotations:
    scheduling.carbon/duration_hours: '1'
    scheduling.carbon/deadline_hours: '25'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m111
  template:
    metadata:
      labels:
        name: m111
      annotations:
        scheduling.carbon/duration_hours: '1'
        scheduling.carbon/deadline_hours: '25'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m112-duration-3h-deadline-27h
  namespace: default
  labels:
    app: m112
    duration: duration-3h
    deadline: deadline-27h
  annotations:
    scheduling.carbon/duration_hours: '3'
    scheduling.carbon/deadline_hours: '27'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m112
  template:
    metadata:
      labels:
        name: m112
      annotations:
        scheduling.carbon/duration_hours: '3'
        scheduling.carbon/deadline_hours: '27'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m113-duration-6h-deadline-8h
  namespace: default
  labels:
    app: m113
    duration: duration-6h
    deadline: deadline-8h
  annotations:
    scheduling.carbon/duration_hours: '6'
    scheduling.carbon/deadline_hours: '8'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m113
  template:
    metadata:
      labels:
        name: m113
      annotations:
        scheduling.carbon/duration_hours: '6'
        scheduling.carbon/deadline_hours: '8'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m114-duration-1h-deadline-7h
  namespace: default
  labels:
    app: m114
    duration: duration-1h
    deadline: deadline-7h
  annotations:
    scheduling.carbon/duration_hours: '1'
    scheduling.carbon/deadline_hours: '7'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m114
  template:
    metadata:
      labels:
        name: m114
      annotations:
        scheduling.carbon/duration_hours: '1'
        scheduling.carbon/deadline_hours: '7'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m115-duration-3h-deadline-5h
  namespace: default
  labels:
    app: m115
    duration: duration-3h
    deadline: deadline-5h
  annotations:
    scheduling.carbon/duration_hours: '3'
    scheduling.carbon/deadline_hours: '5'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m115
  template:
    metadata:
      labels:
        name: m115
      annotations:
        scheduling.carbon/duration_hours: '3'
        scheduling.carbon/deadline_hours: '5'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m116-duration-6h-deadline-12h
  namespace: default
  labels:
    app: m116
    duration: duration-6h
    deadline: deadline-12h
  annotations:
    scheduling.carbon/duration_hours: '6'
    scheduling.carbon/deadline_hours: '12'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m116
  template:
    metadata:
      labels:
        name: m116
      annotations:
        scheduling.carbon/duration_hours: '6'
        scheduling.carbon/deadline_hours: '12'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m117-duration-1h-deadline-3h
  namespace: default
  labels:
    app: m117
    duration: duration-1h
    deadline: deadline-3h
  annotations:
    scheduling.carbon/duration_hours: '1'
    scheduling.carbon/deadline_hours: '3'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m117
  template:
    metadata:
      labels:
        name: m117
      annotations:
        scheduling.carbon/duration_hours: '1'
        scheduling.carbon/deadline_hours: '3'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m118-duration-3h-deadline-9h
  namespace: default
  labels:
    app: m118
    duration: duration-3h
    deadline: deadline-9h
  annotations:
    scheduling.carbon/duration_hours: '3'
    scheduling.carbon/deadline_hours: '9'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m118
  template:
    metadata:
      labels:
        name: m118
      annotations:
        scheduling.carbon/duration_hours: '3'
        scheduling.carbon/deadline_hours: '9'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m119-duration-6h-deadline-8h
  namespace: default
  labels:
    app: m119
    duration: duration-6h
    deadline: deadline-8h
  annotations:
    scheduling.carbon/duration_hours: '6'
    scheduling.carbon/deadline_hours: '8'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m119
  template:
    metadata:
      labels:
        name: m119
      annotations:
        scheduling.carbon/duration_hours: '6'
        scheduling.carbon/deadline_hours: '8'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m120-duration-1h-deadline-7h
  namespace: default
  labels:
    app: m120
    duration: duration-1h
    deadline: deadline-7h
  annotations:
    scheduling.carbon/duration_hours: '1'
    scheduling.carbon/deadline_hours: '7'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m120
  template:
    metadata:
      labels:
        name: m120
      annotations:
        scheduling.carbon/duration_hours: '1'
        scheduling.carbon/deadline_hours: '7'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m121-duration-3h-deadline-27h
  namespace: default
  labels:
    app: m121
    duration: duration-3h
    deadline: deadline-27h
  annotations:
    scheduling.carbon/duration_hours: '3'
    scheduling.carbon/deadline_hours: '27'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m121
  template:
    metadata:
      labels:
        name: m121
      annotations:
        scheduling.carbon/duration_hours: '3'
        scheduling.carbon/deadline_hours: '27'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 1000m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m122-duration-6h-deadline-30h
  namespace: default
  labels:
    app: m122
    duration: duration-6h
    deadline: deadline-30h
  annotations:
    scheduling.carbon/duration_hours: '6'
    scheduling.carbon/deadline_hours: '30'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m122
  template:
    metadata:
      labels:
        name: m122
      annotations:
        scheduling.carbon/duration_hours: '6'
        scheduling.carbon/deadline_hours: '30'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m123-duration-1h-deadline-3h
  namespace: default
  labels:
    app: m123
    duration: duration-1h
    deadline: deadline-3h
  annotations:
    scheduling.carbon/duration_hours: '1'
    scheduling.carbon/deadline_hours: '3'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m123
  template:
    metadata:
      labels:
        name: m123
      annotations:
        scheduling.carbon/duration_hours: '1'
        scheduling.carbon/deadline_hours: '3'
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 500m
---
