apiVersion: apps/v1
kind: Deployment
metadata:
  name: m019
  namespace: default
  labels:
    app: m019
    duration: duration3
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m019
  template:
    metadata:
      labels:
        name: m019
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m020
  namespace: default
  labels:
    app: m020
    duration: duration2
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m020
  template:
    metadata:
      labels:
        name: m020
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m021
  namespace: default
  labels:
    app: m021
    duration: duration3
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m021
  template:
    metadata:
      labels:
        name: m021
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m022
  namespace: default
  labels:
    app: m022
    duration: duration3
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m022
  template:
    metadata:
      labels:
        name: m022
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m023
  namespace: default
  labels:
    app: m023
    duration: duration1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m023
  template:
    metadata:
      labels:
        name: m023
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m024
  namespace: default
  labels:
    app: m024
    duration: duration2
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m024
  template:
    metadata:
      labels:
        name: m024
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m025
  namespace: default
  labels:
    app: m025
    duration: duration1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m025
  template:
    metadata:
      labels:
        name: m025
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m026
  namespace: default
  labels:
    app: m026
    duration: duration2
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m026
  template:
    metadata:
      labels:
        name: m026
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m027
  namespace: default
  labels:
    app: m027
    duration: duration1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m027
  template:
    metadata:
      labels:
        name: m027
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m028
  namespace: default
  labels:
    app: m028
    duration: duration1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m028
  template:
    metadata:
      labels:
        name: m028
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 256Mi
            cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m029
  namespace: default
  labels:
    app: m029
    duration: duration3
spec:
  replicas: 1
  selector:
    matchLabels:
      name: m029
  template:
    metadata:
      labels:
        name: m029
    spec:
      schedulerName: fogatlas
      containers:
      - name: fake-container
        image: fake-image
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
---
