//
// Copyright 2023 FBK.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v4.25.3
// source: idl.proto

package idl

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MicroserviceStatus int32

const (
	MicroserviceStatus_MICROSERVICESTATUS_UNSPECIFIED MicroserviceStatus = 0
	MicroserviceStatus_RUNNING                        MicroserviceStatus = 1
	MicroserviceStatus_PENDING                        MicroserviceStatus = 2
	MicroserviceStatus_TO_SCHEDULE                    MicroserviceStatus = 3
	MicroserviceStatus_TO_DEPLOY                      MicroserviceStatus = 4
)

// Enum value maps for MicroserviceStatus.
var (
	MicroserviceStatus_name = map[int32]string{
		0: "MICROSERVICESTATUS_UNSPECIFIED",
		1: "RUNNING",
		2: "PENDING",
		3: "TO_SCHEDULE",
		4: "TO_DEPLOY",
	}
	MicroserviceStatus_value = map[string]int32{
		"MICROSERVICESTATUS_UNSPECIFIED": 0,
		"RUNNING":                        1,
		"PENDING":                        2,
		"TO_SCHEDULE":                    3,
		"TO_DEPLOY":                      4,
	}
)

func (x MicroserviceStatus) Enum() *MicroserviceStatus {
	p := new(MicroserviceStatus)
	*p = x
	return p
}

func (x MicroserviceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MicroserviceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_idl_proto_enumTypes[0].Descriptor()
}

func (MicroserviceStatus) Type() protoreflect.EnumType {
	return &file_idl_proto_enumTypes[0]
}

func (x MicroserviceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MicroserviceStatus.Descriptor instead.
func (MicroserviceStatus) EnumDescriptor() ([]byte, []int) {
	return file_idl_proto_rawDescGZIP(), []int{0}
}

// The algorithm name.
type AlgorithmName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlgorithmName) Reset() {
	*x = AlgorithmName{}
	mi := &file_idl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlgorithmName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlgorithmName) ProtoMessage() {}

func (x *AlgorithmName) ProtoReflect() protoreflect.Message {
	mi := &file_idl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlgorithmName.ProtoReflect.Descriptor instead.
func (*AlgorithmName) Descriptor() ([]byte, []int) {
	return file_idl_proto_rawDescGZIP(), []int{0}
}

func (x *AlgorithmName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ResourceQuantity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceQuantity) Reset() {
	*x = ResourceQuantity{}
	mi := &file_idl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceQuantity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceQuantity) ProtoMessage() {}

func (x *ResourceQuantity) ProtoReflect() protoreflect.Message {
	mi := &file_idl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceQuantity.ProtoReflect.Descriptor instead.
func (*ResourceQuantity) Descriptor() ([]byte, []int) {
	return file_idl_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceQuantity) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ResourceQuantity) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type Data struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Workload       *Workload              `protobuf:"bytes,1,opt,name=workload,proto3" json:"workload,omitempty"`
	Infrastructure *Infrastructure        `protobuf:"bytes,2,opt,name=infrastructure,proto3" json:"infrastructure,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_idl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_idl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_idl_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetWorkload() *Workload {
	if x != nil {
		return x.Workload
	}
	return nil
}

func (x *Data) GetInfrastructure() *Infrastructure {
	if x != nil {
		return x.Infrastructure
	}
	return nil
}

// The Infrastructure
type Infrastructure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*Node                `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Infrastructure) Reset() {
	*x = Infrastructure{}
	mi := &file_idl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Infrastructure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Infrastructure) ProtoMessage() {}

func (x *Infrastructure) ProtoReflect() protoreflect.Message {
	mi := &file_idl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Infrastructure.ProtoReflect.Descriptor instead.
func (*Infrastructure) Descriptor() ([]byte, []int) {
	return file_idl_proto_rawDescGZIP(), []int{3}
}

func (x *Infrastructure) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CpuUsed       *ResourceQuantity      `protobuf:"bytes,2,opt,name=cpu_used,json=cpuUsed,proto3" json:"cpu_used,omitempty"`
	MemUsed       *ResourceQuantity      `protobuf:"bytes,3,opt,name=mem_used,json=memUsed,proto3" json:"mem_used,omitempty"`
	CpuCap        *ResourceQuantity      `protobuf:"bytes,4,opt,name=cpu_cap,json=cpuCap,proto3" json:"cpu_cap,omitempty"`
	MemCap        *ResourceQuantity      `protobuf:"bytes,5,opt,name=mem_cap,json=memCap,proto3" json:"mem_cap,omitempty"`
	Region        string                 `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	Subcategory   string                 `protobuf:"bytes,7,opt,name=subcategory,proto3" json:"subcategory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_idl_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_idl_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_idl_proto_rawDescGZIP(), []int{4}
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Node) GetCpuUsed() *ResourceQuantity {
	if x != nil {
		return x.CpuUsed
	}
	return nil
}

func (x *Node) GetMemUsed() *ResourceQuantity {
	if x != nil {
		return x.MemUsed
	}
	return nil
}

func (x *Node) GetCpuCap() *ResourceQuantity {
	if x != nil {
		return x.CpuCap
	}
	return nil
}

func (x *Node) GetMemCap() *ResourceQuantity {
	if x != nil {
		return x.MemCap
	}
	return nil
}

func (x *Node) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Node) GetSubcategory() string {
	if x != nil {
		return x.Subcategory
	}
	return ""
}

type Workload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Microservices []*Microservice        `protobuf:"bytes,1,rep,name=microservices,proto3" json:"microservices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workload) Reset() {
	*x = Workload{}
	mi := &file_idl_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workload) ProtoMessage() {}

func (x *Workload) ProtoReflect() protoreflect.Message {
	mi := &file_idl_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workload.ProtoReflect.Descriptor instead.
func (*Workload) Descriptor() ([]byte, []int) {
	return file_idl_proto_rawDescGZIP(), []int{5}
}

func (x *Workload) GetMicroservices() []*Microservice {
	if x != nil {
		return x.Microservices
	}
	return nil
}

type Microservice struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Replicas    int32                  `protobuf:"varint,2,opt,name=replicas,proto3" json:"replicas,omitempty"`
	CpuRequired *ResourceQuantity      `protobuf:"bytes,3,opt,name=cpu_required,json=cpuRequired,proto3" json:"cpu_required,omitempty"`
	MemRequired *ResourceQuantity      `protobuf:"bytes,4,opt,name=mem_required,json=memRequired,proto3" json:"mem_required,omitempty"`
	Status      MicroserviceStatus     `protobuf:"varint,5,opt,name=status,proto3,enum=idl.MicroserviceStatus" json:"status,omitempty"`
	// Nodes where ms is deployed (for each replica) if status is RUNNING
	DeployedOn []string `protobuf:"bytes,6,rep,name=deployed_on,json=deployedOn,proto3" json:"deployed_on,omitempty"`
	// How long the workload runs
	DurationHours string `protobuf:"bytes,7,opt,name=duration_hours,json=durationHours,proto3" json:"duration_hours,omitempty"`
	// Hours until deployment deadline
	DeadlineHours string `protobuf:"bytes,8,opt,name=deadline_hours,json=deadlineHours,proto3" json:"deadline_hours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Microservice) Reset() {
	*x = Microservice{}
	mi := &file_idl_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Microservice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Microservice) ProtoMessage() {}

func (x *Microservice) ProtoReflect() protoreflect.Message {
	mi := &file_idl_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Microservice.ProtoReflect.Descriptor instead.
func (*Microservice) Descriptor() ([]byte, []int) {
	return file_idl_proto_rawDescGZIP(), []int{6}
}

func (x *Microservice) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Microservice) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *Microservice) GetCpuRequired() *ResourceQuantity {
	if x != nil {
		return x.CpuRequired
	}
	return nil
}

func (x *Microservice) GetMemRequired() *ResourceQuantity {
	if x != nil {
		return x.MemRequired
	}
	return nil
}

func (x *Microservice) GetStatus() MicroserviceStatus {
	if x != nil {
		return x.Status
	}
	return MicroserviceStatus_MICROSERVICESTATUS_UNSPECIFIED
}

func (x *Microservice) GetDeployedOn() []string {
	if x != nil {
		return x.DeployedOn
	}
	return nil
}

func (x *Microservice) GetDurationHours() string {
	if x != nil {
		return x.DurationHours
	}
	return ""
}

func (x *Microservice) GetDeadlineHours() string {
	if x != nil {
		return x.DeadlineHours
	}
	return ""
}

type Placements struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Placements    []*Placement           `protobuf:"bytes,1,rep,name=placements,proto3" json:"placements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Placements) Reset() {
	*x = Placements{}
	mi := &file_idl_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Placements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Placements) ProtoMessage() {}

func (x *Placements) ProtoReflect() protoreflect.Message {
	mi := &file_idl_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Placements.ProtoReflect.Descriptor instead.
func (*Placements) Descriptor() ([]byte, []int) {
	return file_idl_proto_rawDescGZIP(), []int{7}
}

func (x *Placements) GetPlacements() []*Placement {
	if x != nil {
		return x.Placements
	}
	return nil
}

// One placement for each microservice
type Placement struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MicroserviceName string                 `protobuf:"bytes,1,opt,name=microservice_name,json=microserviceName,proto3" json:"microservice_name,omitempty"`
	// For all the replicas
	ReplicaScores []*ReplicaScores `protobuf:"bytes,2,rep,name=replica_scores,json=replicaScores,proto3" json:"replica_scores,omitempty"`
	// In Unix time (seconds)
	TimeToSchedule int64 `protobuf:"varint,3,opt,name=time_to_schedule,json=timeToSchedule,proto3" json:"time_to_schedule,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Placement) Reset() {
	*x = Placement{}
	mi := &file_idl_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Placement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Placement) ProtoMessage() {}

func (x *Placement) ProtoReflect() protoreflect.Message {
	mi := &file_idl_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Placement.ProtoReflect.Descriptor instead.
func (*Placement) Descriptor() ([]byte, []int) {
	return file_idl_proto_rawDescGZIP(), []int{8}
}

func (x *Placement) GetMicroserviceName() string {
	if x != nil {
		return x.MicroserviceName
	}
	return ""
}

func (x *Placement) GetReplicaScores() []*ReplicaScores {
	if x != nil {
		return x.ReplicaScores
	}
	return nil
}

func (x *Placement) GetTimeToSchedule() int64 {
	if x != nil {
		return x.TimeToSchedule
	}
	return 0
}

type ReplicaScores struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scores        []*Score               `protobuf:"bytes,1,rep,name=scores,proto3" json:"scores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaScores) Reset() {
	*x = ReplicaScores{}
	mi := &file_idl_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaScores) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaScores) ProtoMessage() {}

func (x *ReplicaScores) ProtoReflect() protoreflect.Message {
	mi := &file_idl_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaScores.ProtoReflect.Descriptor instead.
func (*ReplicaScores) Descriptor() ([]byte, []int) {
	return file_idl_proto_rawDescGZIP(), []int{9}
}

func (x *ReplicaScores) GetScores() []*Score {
	if x != nil {
		return x.Scores
	}
	return nil
}

type Score struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Score         int32                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Score) Reset() {
	*x = Score{}
	mi := &file_idl_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Score) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Score) ProtoMessage() {}

func (x *Score) ProtoReflect() protoreflect.Message {
	mi := &file_idl_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Score.ProtoReflect.Descriptor instead.
func (*Score) Descriptor() ([]byte, []int) {
	return file_idl_proto_rawDescGZIP(), []int{10}
}

func (x *Score) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *Score) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_idl_proto protoreflect.FileDescriptor

var file_idl_proto_rawDesc = string([]byte{
	0x0a, 0x09, 0x69, 0x64, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x69, 0x64, 0x6c,
	0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x23, 0x0a,
	0x0d, 0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x40, 0x0a, 0x10, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x51, 0x75,
	0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x22, 0x6e, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x29, 0x0a, 0x08,
	0x77, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x69, 0x64, 0x6c, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x08, 0x77,
	0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x3b, 0x0a, 0x0e, 0x69, 0x6e, 0x66, 0x72, 0x61,
	0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x69, 0x64, 0x6c, 0x2e, 0x49, 0x6e, 0x66, 0x72, 0x61, 0x73, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x75, 0x72, 0x65, 0x52, 0x0e, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x73, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x75, 0x72, 0x65, 0x22, 0x31, 0x0a, 0x0e, 0x49, 0x6e, 0x66, 0x72, 0x61, 0x73, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1f, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x69, 0x64, 0x6c, 0x2e, 0x4e, 0x6f, 0x64, 0x65,
	0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x22, 0x98, 0x02, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x30, 0x0a, 0x08, 0x63, 0x70, 0x75, 0x5f, 0x75, 0x73, 0x65, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x69, 0x64, 0x6c, 0x2e, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x07, 0x63,
	0x70, 0x75, 0x55, 0x73, 0x65, 0x64, 0x12, 0x30, 0x0a, 0x08, 0x6d, 0x65, 0x6d, 0x5f, 0x75, 0x73,
	0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x69, 0x64, 0x6c, 0x2e, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52,
	0x07, 0x6d, 0x65, 0x6d, 0x55, 0x73, 0x65, 0x64, 0x12, 0x2e, 0x0a, 0x07, 0x63, 0x70, 0x75, 0x5f,
	0x63, 0x61, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x69, 0x64, 0x6c, 0x2e,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x52, 0x06, 0x63, 0x70, 0x75, 0x43, 0x61, 0x70, 0x12, 0x2e, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x5f,
	0x63, 0x61, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x69, 0x64, 0x6c, 0x2e,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x52, 0x06, 0x6d, 0x65, 0x6d, 0x43, 0x61, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69,
	0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x12, 0x20, 0x0a, 0x0b, 0x73, 0x75, 0x62, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x75, 0x62, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x22, 0x43, 0x0a, 0x08, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x37,
	0x0a, 0x0d, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x69, 0x64, 0x6c, 0x2e, 0x4d, 0x69, 0x63, 0x72,
	0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x0d, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x22, 0xd2, 0x02, 0x0a, 0x0c, 0x4d, 0x69, 0x63, 0x72,
	0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x12, 0x38, 0x0a, 0x0c, 0x63, 0x70, 0x75, 0x5f,
	0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x69, 0x64, 0x6c, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x51, 0x75, 0x61,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x0b, 0x63, 0x70, 0x75, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72,
	0x65, 0x64, 0x12, 0x38, 0x0a, 0x0c, 0x6d, 0x65, 0x6d, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72,
	0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x69, 0x64, 0x6c, 0x2e, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52,
	0x0b, 0x6d, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x12, 0x2f, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x69,
	0x64, 0x6c, 0x2e, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1f, 0x0a,
	0x0b, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x64, 0x5f, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0a, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x64, 0x4f, 0x6e, 0x12, 0x25,
	0x0a, 0x0e, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x68, 0x6f, 0x75, 0x72, 0x73,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x48, 0x6f, 0x75, 0x72, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x64, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e,
	0x65, 0x5f, 0x68, 0x6f, 0x75, 0x72, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x64,
	0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x22, 0x3c, 0x0a, 0x0a,
	0x50, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x2e, 0x0a, 0x0a, 0x70, 0x6c,
	0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x69, 0x64, 0x6c, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0a,
	0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x9d, 0x01, 0x0a, 0x09, 0x50,
	0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x2b, 0x0a, 0x11, 0x6d, 0x69, 0x63, 0x72,
	0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x10, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x39, 0x0a, 0x0e, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x69, 0x64, 0x6c, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x53, 0x63, 0x6f, 0x72, 0x65,
	0x73, 0x52, 0x0d, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73,
	0x12, 0x28, 0x0a, 0x10, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x74, 0x6f, 0x5f, 0x73, 0x63, 0x68, 0x65,
	0x64, 0x75, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x74, 0x69, 0x6d, 0x65,
	0x54, 0x6f, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x22, 0x33, 0x0a, 0x0d, 0x52, 0x65,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x12, 0x22, 0x0a, 0x06, 0x73,
	0x63, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x69, 0x64,
	0x6c, 0x2e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x06, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x22,
	0x31, 0x0a, 0x05, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x63, 0x6f,
	0x72, 0x65, 0x2a, 0x72, 0x0a, 0x12, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x22, 0x0a, 0x1e, 0x4d, 0x49, 0x43, 0x52,
	0x4f, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07,
	0x52, 0x55, 0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x45, 0x4e,
	0x44, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x4f, 0x5f, 0x53, 0x43, 0x48,
	0x45, 0x44, 0x55, 0x4c, 0x45, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x4f, 0x5f, 0x44, 0x45,
	0x50, 0x4c, 0x4f, 0x59, 0x10, 0x04, 0x32, 0x7e, 0x0a, 0x12, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x12, 0x34, 0x0a, 0x04,
	0x49, 0x6e, 0x69, 0x74, 0x12, 0x12, 0x2e, 0x69, 0x64, 0x6c, 0x2e, 0x41, 0x6c, 0x67, 0x6f, 0x72,
	0x69, 0x74, 0x68, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x22, 0x00, 0x12, 0x32, 0x0a, 0x12, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x50,
	0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x09, 0x2e, 0x69, 0x64, 0x6c, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x1a, 0x0f, 0x2e, 0x69, 0x64, 0x6c, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x22, 0x00, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x69, 0x64, 0x6c, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_idl_proto_rawDescOnce sync.Once
	file_idl_proto_rawDescData []byte
)

func file_idl_proto_rawDescGZIP() []byte {
	file_idl_proto_rawDescOnce.Do(func() {
		file_idl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_idl_proto_rawDesc), len(file_idl_proto_rawDesc)))
	})
	return file_idl_proto_rawDescData
}

var file_idl_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_idl_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_idl_proto_goTypes = []any{
	(MicroserviceStatus)(0),  // 0: idl.MicroserviceStatus
	(*AlgorithmName)(nil),    // 1: idl.AlgorithmName
	(*ResourceQuantity)(nil), // 2: idl.ResourceQuantity
	(*Data)(nil),             // 3: idl.Data
	(*Infrastructure)(nil),   // 4: idl.Infrastructure
	(*Node)(nil),             // 5: idl.Node
	(*Workload)(nil),         // 6: idl.Workload
	(*Microservice)(nil),     // 7: idl.Microservice
	(*Placements)(nil),       // 8: idl.Placements
	(*Placement)(nil),        // 9: idl.Placement
	(*ReplicaScores)(nil),    // 10: idl.ReplicaScores
	(*Score)(nil),            // 11: idl.Score
	(*emptypb.Empty)(nil),    // 12: google.protobuf.Empty
}
var file_idl_proto_depIdxs = []int32{
	6,  // 0: idl.Data.workload:type_name -> idl.Workload
	4,  // 1: idl.Data.infrastructure:type_name -> idl.Infrastructure
	5,  // 2: idl.Infrastructure.nodes:type_name -> idl.Node
	2,  // 3: idl.Node.cpu_used:type_name -> idl.ResourceQuantity
	2,  // 4: idl.Node.mem_used:type_name -> idl.ResourceQuantity
	2,  // 5: idl.Node.cpu_cap:type_name -> idl.ResourceQuantity
	2,  // 6: idl.Node.mem_cap:type_name -> idl.ResourceQuantity
	7,  // 7: idl.Workload.microservices:type_name -> idl.Microservice
	2,  // 8: idl.Microservice.cpu_required:type_name -> idl.ResourceQuantity
	2,  // 9: idl.Microservice.mem_required:type_name -> idl.ResourceQuantity
	0,  // 10: idl.Microservice.status:type_name -> idl.MicroserviceStatus
	9,  // 11: idl.Placements.placements:type_name -> idl.Placement
	10, // 12: idl.Placement.replica_scores:type_name -> idl.ReplicaScores
	11, // 13: idl.ReplicaScores.scores:type_name -> idl.Score
	1,  // 14: idl.PlacementAlgorithm.Init:input_type -> idl.AlgorithmName
	3,  // 15: idl.PlacementAlgorithm.CalculatePlacement:input_type -> idl.Data
	12, // 16: idl.PlacementAlgorithm.Init:output_type -> google.protobuf.Empty
	8,  // 17: idl.PlacementAlgorithm.CalculatePlacement:output_type -> idl.Placements
	16, // [16:18] is the sub-list for method output_type
	14, // [14:16] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_idl_proto_init() }
func file_idl_proto_init() {
	if File_idl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_idl_proto_rawDesc), len(file_idl_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_idl_proto_goTypes,
		DependencyIndexes: file_idl_proto_depIdxs,
		EnumInfos:         file_idl_proto_enumTypes,
		MessageInfos:      file_idl_proto_msgTypes,
	}.Build()
	File_idl_proto = out.File
	file_idl_proto_goTypes = nil
	file_idl_proto_depIdxs = nil
}
