//
// Copyright 2023 FBK.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: idl.proto

package idl

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlacementAlgorithm_Init_FullMethodName               = "/idl.PlacementAlgorithm/Init"
	PlacementAlgorithm_CalculatePlacement_FullMethodName = "/idl.PlacementAlgorithm/CalculatePlacement"
)

// PlacementAlgorithmClient is the client API for PlacementAlgorithm service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The placement algorithm service definition.
type PlacementAlgorithmClient interface {
	Init(ctx context.Context, in *AlgorithmName, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CalculatePlacement(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Placements, error)
}

type placementAlgorithmClient struct {
	cc grpc.ClientConnInterface
}

func NewPlacementAlgorithmClient(cc grpc.ClientConnInterface) PlacementAlgorithmClient {
	return &placementAlgorithmClient{cc}
}

func (c *placementAlgorithmClient) Init(ctx context.Context, in *AlgorithmName, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PlacementAlgorithm_Init_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *placementAlgorithmClient) CalculatePlacement(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Placements, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Placements)
	err := c.cc.Invoke(ctx, PlacementAlgorithm_CalculatePlacement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlacementAlgorithmServer is the server API for PlacementAlgorithm service.
// All implementations must embed UnimplementedPlacementAlgorithmServer
// for forward compatibility.
//
// The placement algorithm service definition.
type PlacementAlgorithmServer interface {
	Init(context.Context, *AlgorithmName) (*emptypb.Empty, error)
	CalculatePlacement(context.Context, *Data) (*Placements, error)
	mustEmbedUnimplementedPlacementAlgorithmServer()
}

// UnimplementedPlacementAlgorithmServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlacementAlgorithmServer struct{}

func (UnimplementedPlacementAlgorithmServer) Init(context.Context, *AlgorithmName) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedPlacementAlgorithmServer) CalculatePlacement(context.Context, *Data) (*Placements, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculatePlacement not implemented")
}
func (UnimplementedPlacementAlgorithmServer) mustEmbedUnimplementedPlacementAlgorithmServer() {}
func (UnimplementedPlacementAlgorithmServer) testEmbeddedByValue()                            {}

// UnsafePlacementAlgorithmServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlacementAlgorithmServer will
// result in compilation errors.
type UnsafePlacementAlgorithmServer interface {
	mustEmbedUnimplementedPlacementAlgorithmServer()
}

func RegisterPlacementAlgorithmServer(s grpc.ServiceRegistrar, srv PlacementAlgorithmServer) {
	// If the following call pancis, it indicates UnimplementedPlacementAlgorithmServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlacementAlgorithm_ServiceDesc, srv)
}

func _PlacementAlgorithm_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlgorithmName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlacementAlgorithmServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlacementAlgorithm_Init_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlacementAlgorithmServer).Init(ctx, req.(*AlgorithmName))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlacementAlgorithm_CalculatePlacement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Data)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlacementAlgorithmServer).CalculatePlacement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlacementAlgorithm_CalculatePlacement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlacementAlgorithmServer).CalculatePlacement(ctx, req.(*Data))
	}
	return interceptor(ctx, in, info, handler)
}

// PlacementAlgorithm_ServiceDesc is the grpc.ServiceDesc for PlacementAlgorithm service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlacementAlgorithm_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "idl.PlacementAlgorithm",
	HandlerType: (*PlacementAlgorithmServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _PlacementAlgorithm_Init_Handler,
		},
		{
			MethodName: "CalculatePlacement",
			Handler:    _PlacementAlgorithm_CalculatePlacement_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "idl.proto",
}
