// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: idl.proto

package idl

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PlacementAlgorithmClient is the client API for PlacementAlgorithm service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlacementAlgorithmClient interface {
	Init(ctx context.Context, in *AlgorithmName, opts ...grpc.CallOption) (*empty.Empty, error)
	CalculatePlacement(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Workload, error)
}

type placementAlgorithmClient struct {
	cc grpc.ClientConnInterface
}

func NewPlacementAlgorithmClient(cc grpc.ClientConnInterface) PlacementAlgorithmClient {
	return &placementAlgorithmClient{cc}
}

func (c *placementAlgorithmClient) Init(ctx context.Context, in *AlgorithmName, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/idl.PlacementAlgorithm/Init", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *placementAlgorithmClient) CalculatePlacement(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Workload, error) {
	out := new(Workload)
	err := c.cc.Invoke(ctx, "/idl.PlacementAlgorithm/CalculatePlacement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlacementAlgorithmServer is the server API for PlacementAlgorithm service.
// All implementations must embed UnimplementedPlacementAlgorithmServer
// for forward compatibility
type PlacementAlgorithmServer interface {
	Init(context.Context, *AlgorithmName) (*empty.Empty, error)
	CalculatePlacement(context.Context, *Data) (*Workload, error)
	mustEmbedUnimplementedPlacementAlgorithmServer()
}

// UnimplementedPlacementAlgorithmServer must be embedded to have forward compatible implementations.
type UnimplementedPlacementAlgorithmServer struct {
}

func (UnimplementedPlacementAlgorithmServer) Init(context.Context, *AlgorithmName) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedPlacementAlgorithmServer) CalculatePlacement(context.Context, *Data) (*Workload, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculatePlacement not implemented")
}
func (UnimplementedPlacementAlgorithmServer) mustEmbedUnimplementedPlacementAlgorithmServer() {}

// UnsafePlacementAlgorithmServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlacementAlgorithmServer will
// result in compilation errors.
type UnsafePlacementAlgorithmServer interface {
	mustEmbedUnimplementedPlacementAlgorithmServer()
}

func RegisterPlacementAlgorithmServer(s grpc.ServiceRegistrar, srv PlacementAlgorithmServer) {
	s.RegisterService(&PlacementAlgorithm_ServiceDesc, srv)
}

func _PlacementAlgorithm_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlgorithmName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlacementAlgorithmServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.PlacementAlgorithm/Init",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlacementAlgorithmServer).Init(ctx, req.(*AlgorithmName))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlacementAlgorithm_CalculatePlacement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Data)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlacementAlgorithmServer).CalculatePlacement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.PlacementAlgorithm/CalculatePlacement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlacementAlgorithmServer).CalculatePlacement(ctx, req.(*Data))
	}
	return interceptor(ctx, in, info, handler)
}

// PlacementAlgorithm_ServiceDesc is the grpc.ServiceDesc for PlacementAlgorithm service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlacementAlgorithm_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "idl.PlacementAlgorithm",
	HandlerType: (*PlacementAlgorithmServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _PlacementAlgorithm_Init_Handler,
		},
		{
			MethodName: "CalculatePlacement",
			Handler:    _PlacementAlgorithm_CalculatePlacement_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "idl.proto",
}
