/*
 * Copyright 2023 FBK.
 *  
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *  
 *      http://www.apache.org/licenses/LICENSE-2.0
 *  
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

syntax = "proto3";

import "google/protobuf/empty.proto";

option go_package = "./idl";

package idl;

// The placement algorithm service definition.
service PlacementAlgorithm {
	rpc Init(AlgorithmName) returns (google.protobuf.Empty) {}
	rpc CalculatePlacement(Data) returns (Placements) {}
}

enum MicroserviceStatus {
	MICROSERVICESTATUS_UNSPECIFIED = 0;
	RUNNING = 1;
	PENDING = 2;
	TO_SCHEDULE = 3;
	TO_DEPLOY = 4;
}

// The algorithm name.
message AlgorithmName {
	string name = 1;
}

message ResourceQuantity {
	string value = 1;
  	string format = 2;
}

message Data {
	Workload workload = 1;
  	Infrastructure infrastructure = 2;
}

// The Infrastructure
message Infrastructure {
	repeated Node nodes = 1;
}

message Node {
	string name = 1;
	ResourceQuantity cpu_used  = 2; 
	ResourceQuantity mem_used = 3;  
	ResourceQuantity cpu_cap  = 4;  
	ResourceQuantity mem_cap  = 5;  
	string region = 6;
	string subcategory = 7;
}

message Workload {
	repeated Microservice microservices  = 1;         
}

message Microservice {
  string name = 1;
  MicroserviceStatus status = 2;
  repeated string deployed_on = 3;
  int32 replicas = 4;
  ResourceQuantity cpu_required = 5;
  ResourceQuantity mem_required = 6;
  
  // Changed from double to string
  string duration = 7;  // How long the workload runs (e.g. "1h", "90m")
  string deadline = 8;  // When it must complete by (e.g. "24h", "1d")
}

message Placements {
	repeated Placement placements  = 1;    
}

// One placement for each microservice
message Placement {
	string microservice_name = 1;
	// For all the replicas	
	repeated ReplicaScores replica_scores = 2;
	// In Unix time (seconds)
	int64 time_to_schedule = 3;
}

message ReplicaScores {
	repeated Score scores = 1;
}

message Score {
	string node = 1;
	int32 score = 2;
}
